### ISSUE TITLE
Error when deploying API Gateway

### ISSUE THREAD

**Issue by ivchicano** [micado-eu/micado_deployment#17]
I tried to redeploy everything and get a Bad Gateway error when connecting to the API manager.
For context I had to create the following directories to deploy:  

`mkdir db_data weblate_data redis_data identity-server_data/deployment identity-server_data/tenants shared_images`

The log obtained by docker container logs can be found in the attached file.
[api_gateway_log.txt](https://github.com/micado-eu/micado_deployment/files/5589237/api_gateway_log.txt)

**Comment by ivchicano** [comment]
I still get 502 Bad Gateway error but I managed to fix the permissions error by changing the owner of the volume:
`sudo chown -R 802 api_manager_data`
But now I get the error in this log:
[api_gateway_log (2).txt](https://github.com/micado-eu/micado_deployment/files/5616453/api_gateway_log.2.txt)

**Comment by gioppoluca** [comment]
Have changed the volume mounts for the api manager, but will have to find a better solution.

**Comment by gioppoluca** [comment]
does it work with the current compose file?

**Comment by ivchicano** [comment]
At the moment this is working
