### ISSUE TITLE
PA app doesn't substitute the template config file with the environment variables

### ISSUE THREAD

**Issue by ivchicano** [micado-eu/micado_deployment#18]
The data_pa component doesn't have envsubst (I assume gettext isn't installed in this container). The data_ngo component doesn't have this problem and does the correct substitution.

Looking at the [Dockerfile of the image](https://hub.docker.com/r/micadoproject/pa_app_site/dockerfile) in Docker Hub seems like the following line should be added to the Dockerfile (I can't find the Dockerfile in any repository or I would add it myself):

`RUN apk add --no-cache gettext`

Log from docker-compose logs data_pa:
data_pa_1             | total 8
data_pa_1             | drwxr-xr-x    1 root     root          4096 Nov 24 09:56 ..
data_pa_1             | drwxr-xr-x    2 root     root          4096 Nov 24 09:21 .
data_pa_1             | total 28
data_pa_1             | sh: envsubst: not found
data_pa_1             | drwxr-xr-x    6 root     root          4096 Nov 24 09:56 .
data_pa_1             | drwxr-xr-x    1 root     root          4096 Nov 24 09:56 ..
data_pa_1             | drwxr-xr-x    2 1000     1000          4096 Nov 24 09:56 css
data_pa_1             | drwxr-xr-x    2 1000     1000          4096 Nov 24 09:56 fonts
data_pa_1             | drwxr-xr-x    2 1000     1000          4096 Nov 24 09:56 js
data_pa_1             | drwxr-xr-x    4 1000     1000          4096 Nov 24 09:56 statics
data_pa_1             | -rw-r--r--    1 1000     1000          1160 Nov 23 16:50 index.html

**Comment by gioppoluca** [comment]
Fixed with latest redeploy
