### ISSUE TITLE
Acme.json missing in traefik

### ISSUE THREAD

**Issue by ivchicano** [micado-eu/micado_deployment#23]
Inside the traefik/traefik-acme directory there should be a file called acme.json. If this file doesn't exist, the docker-compose creates a directory there, causing the balancer to not pick up the certificates.
I would make a pull request but I dont' have permissions in this repo.

**Comment by gioppoluca** [comment]
Yes you have to create folder and file in your environment.
Please update the wiki documentation on this.
That file is the one that traefik use to save and persist the certificates so that it does not consume all the requests that it can do to let' encrypt

**Comment by ivchicano** [comment]
I have updated the wiki documentation with the information
