### ISSUE TITLE
Error 500 when querying api manager

### ISSUE THREAD

**Issue by ivchicano** [micado-eu/micado_deployment#24]
I get an error 500 on any query to the api manager with the following error:
```xml
<soapenv:Reason xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope">
    <soapenv:Text xml:lang="en-US">JSONObject["kid"] not found.</soapenv:Text>
</soapenv:Reason>
```
When decoding the JWT I found out there is a header missing that should be there (when decoding the staging environment JWT it shows this header). I suspect it might be related to the keystore in the api manager. Is it hardcoded?

**Comment by gioppoluca** [comment]
need to have more info on this
have you checked the API manager logs?

**Comment by ivchicano** [comment]
I attach the logs in this comment.
[api_gateways_logs.log](https://github.com/micado-eu/micado_deployment/files/5687429/api_gateways_logs.log)

**Comment by gioppoluca** [comment]
have you managed to fix this issue?
I do not understand the error you are getting and also the context.
Are you trying to use postman and not micado?
because in this case you do not need to create any jwt you need to just send the api key in the header.

**Comment by ivchicano** [comment]
I used postman because when deploying micado does not work. The token used in the apikey header that is generated by the gateway when generating the api key is a JWT. The error still persists. I attach here a screenshot of the postman request.
![Postman_wUQdr0ItJD](https://user-images.githubusercontent.com/46921761/104306797-ad27e080-54ce-11eb-83aa-1fd7c02dce37.png)

**Comment by ivchicano** [comment]
Fixed, I was making a mistake when creating the api key, I will update the documentation to be more clear in this aspect.
