### ISSUE TITLE
Fill prod.env cert password/alias variables or let the user choose the password

### ISSUE THREAD

**Issue by ivchicano** [micado-eu/micado_deployment#33]
Either the user should be able to choose the password of the certificates generated by keytool in the install_micado.sh script, or the prod.env file should be filled with the chosen password/alias.
Also, there seems to be a typo in this line (keypass argument, ws2carbon instead of wso2carbon with an 'o' before the 2)
https://github.com/micado-eu/micado_deployment/blob/31ad12251828d3c42c64424c32da360db9f5cdab/install_micado.sh#L28

**Comment by gioppoluca** [comment]
These certificates are used internally so is correct that we pre-fill those info in the prod.env
