### ISSUE TITLE
Error on PA log in

### ISSUE THREAD

**Issue by ivchicano** [micado-eu/micado_deployment#48]
When trying to log in to the PA application, it redirects me to a white page.

On deployment the PA app looks like this:
![Screenshot from 2021-04-23 10-34-01](https://user-images.githubusercontent.com/46921761/115843781-7e030280-a41f-11eb-925c-1992f317b071.png)

The rest of the applications look normal.

I will copy here the relevant information of my emails with @GiuseppeCSI where we try to solve the issue:

> Aa a side note,  i was looking at the backend logs you posted with the deployment issue and it seems that the user you are trying to log in with does not have a tenant. Could you check  on the um_user table in the wso2_shared schema if the um_tenant_id table is empty or not? The issue should lie there

About the deployment issue, the first row (which I assume is the migrant tenant as it is the one with the earliest date) has a um_tenant_id of -1234 and the second row (which I assume is the PA) has a um_tenant_id of 1

> About this issue,since the tenants are there, my second question is: did you modify the settings table in the db in any way? The error you get should be from the verify function in the verification page when it calls the fetchUserLogin function. In that function he takes the pa tenant or migrant tentant (which should be the one that for you are undefined) from a variable set in the loaddata.js, which in turn takes it from the settings table in the db. So try to check that. If everything is in order even there then I will take a more thorough look with Luca when i can.

I haven’t touched the settings table, I just installed micado and then tried to log in with the PA app. Also the translated labels are not working (For example in the menu I see menu.login instead of Login), which I assume is an issue with not having deployed gitea and weblate correctly (I already opened an issue about this in the micado_deployment repo).

I attach a screenshot of the table setting in pgadmin.

![pgadmin](https://user-images.githubusercontent.com/46921761/115843863-94a95980-a41f-11eb-93f3-dc4b51e8069c.png)

Backend log
``

> backend_1             | (node:1) ExperimentalWarning: The fs.promises API is experimental
backend_1             | SONO QUI
backend_1             | RSwAbICtX3kep6hsrGFw
backend_1             | { name: 'micadoDS',
backend_1             |   connector: 'postgresql',
backend_1             |   url: 'postgres://micadoapp:micadoapp@micado_db/micado',
backend_1             |   host: 'micado_db',
backend_1             |   port: 5432,
backend_1             |   user: 'micadoapp',
backend_1             |   password: 'process.env.MICADO_DB_PWD',
backend_1             |   schema: 'micadoapp',
backend_1             |   migrationCreateSchema: false,
backend_1             |   database: 'micado' }
backend_1             | { name: 'micadoDS',
backend_1             |   connector: 'postgresql',
backend_1             |   url: 'postgres://micadoapp:RSwAbICtX3kep6hsrGFw@micado_db/micado',
backend_1             |   host: 'micado_db',
backend_1             |   port: 5432,
backend_1             |   user: 'micadoapp',
backend_1             |   password: 'RSwAbICtX3kep6hsrGFw',
backend_1             |   schema: 'micadoapp',
backend_1             |   migrationCreateSchema: false,
backend_1             |   database: 'micado' }
backend_1             | Server is running at http://172.24.0.9:3000
backend_1             | Try http://172.24.0.9:3000/ping
backend_1             | Started Event Deleter Cron
backend_1             | Unhandled error in GET /users?filter[include][0][relation]=attributes&filter[include][1][relation]=interventionPlans&filter[where][and][0][umUserName][eq]=admin&filter[where][and][1][umTenantId]=undefined&filter[fields]=umId: 500 error: invalid input syntax for integer: "undefined"
backend_1             |     at Connection.parseE (/home/node/app/node_modules/pg/lib/connection.js:581:48)
backend_1             |     at Connection.parseMessage (/home/node/app/node_modules/pg/lib/connection.js:380:19)
backend_1             |     at Socket.<anonymous> (/home/node/app/node_modules/pg/lib/connection.js:116:22)
backend_1             |     at Socket.emit (events.js:198:13)
backend_1             |     at addChunk (_stream_readable.js:288:12)
backend_1             |     at readableAddChunk (_stream_readable.js:269:11)
backend_1             |     at Socket.Readable.push (_stream_readable.js:224:10)
backend_1             |     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by gioppoluca** [comment]
If I understand well you try to login but I do not understand IF you manage to login or you do not reach the identity server at all? 

/users?filter[include][0][relation]=attributes&filter[include][1][relation]=interventionPlans&filter[where][and][0][umUserName][eq]=admin&filter[where][and][1][umTenantId]=undefined&filter[fields]=umId: 500 error: invalid input syntax for integer: "undefined"

In this call the umTenantId is undefined so there is some configuration error previously probably
Can you write the PA url so we can see the error in the console?
Thanks

**Comment by ivchicano** [comment]
It doesn't seem to reach the identity server as I am not logged in after putting in my credentials and signing in.
The PA url is the following:
https://pa.micado.codeurjc.es/
I will send you the credentials by email.

**Comment by gioppoluca** [comment]
Found the error
In the settings table the "translationState" json has a newline in one KEY nd so it is broken this generate en error in the loadData boot and you end up NOT having the right tenant (since is the next instruction and the error makes it jump)

[{"value":0,"translation":[{"lang":"en", "state":"Editing"}, {"lang":"it", "state":"Modifica"}, {"lang":"es", "state":"Edición"}, {"lang":"de", "state"
:"Bearbeitung"}, {"lang":"nl", "state":"Bewerken"}]},
{"value":1,"translation":[{"lang":"en", "state":"Translatable"}, {"lang":"it", "state":"Traducibile"}, {"lang":"es", "state":"Traducible"}, {"lang":"de", "state":"Übersetzbar"}, {"lang":"nl", "state":"Vertaalbaar"}]},
{"value":2,"translation":[{"lang":"en", "state":"Translating"}, {"lang":"it", "state":"In traduzione"}, {"lang":"es", "state":"Traductorio"}, {"lang":"de", "state":"Übersetzen"}, {"lang":"nl", "state":"Vertalen"
}]},
{"value":3,"translation":[{"lang":"en", "state":"Translated"}, {"lang":"it", "state":"Tradotto"}, {"lang":"es", "state":"Traducido"}, {"lang":"de", "state":"Übersetzt"}, {"lang":"nl", "state":"Vertaald"}]}
]

This is the json please check it out with a json parser and than with pgadmin update the content this should fix the problem

Will obviously fix the DB setting in the beginning.
@JowieXiang  read this since it could affect you as well.

It fixes close it

**Comment by ivchicano** [comment]
Looks like this fixed it, now I can log in and use the application
